server:
  image: willko/go-echo-server-demo:latest
  ports:
    - 3000:3000
  links:
    - db
  environment:
    - APP_PORT=3000
db:
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
  image: 'postgres:9.6'
  ports:
    - '5432:5432'
